FROM registry.access.redhat.com/ubi8/openjdk-11:1.16-3 AS builder
ADD . .
RUN mkdir -p target && mvn clean package -s settings.xml

# FROM registry.access.redhat.com/ubi8/openjdk-11:1.16-3
# COPY --from=builder . .
# EXPOSE 3000
# CMD mvn exec:java