---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-api
    provider: jkube
    version: "1.0"
    group: com.redhat.training.openshift.todoapi
  name: todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
      provider: jkube
      group: com.redhat.training.openshift.todoapi
  template:
    metadata:
      labels:
        app: todo-api
        provider: jkube
        version: "1.0"
        group: com.redhat.training.openshift.todoapi
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
          image: quay.io/jkube/jkube-java-binary-s2i:0.0.9
        envFrom:
        - configMapRef:
            name: configmap-todo
        imagePullPolicy: IfNotPresent
        name: quarkus
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        securityContext:
          privileged: false