apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-java-pipeline
spec:
  workspaces:
    - name: shared
    # - name: maven_configs
  params:
    - name: GIT_REPO
      type: string
      default: "https://github.com/mikelo/DO288-apps"
    - name: GIT_REVISION
      type: string
      default: "pipeline"
    - name: APP_PATH
      type: string
      default: "builds-applications/apps/vertx-site"
    - name: DEPLOY_ARTIFACT_NAME
      type: string
      default: "target/vertx-site-1.0.0-SNAPSHOT-fat.jar"
    - name: DEPLOY_APP_NAME
      type: string
      default: "vertx-site"

  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: sslVerify
          value: "false"
      workspaces:
        - name: output
          workspace: shared

    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          # value: image-registry.openshift-image-registry.svc:5000/pipelines-review/$(params.DEPLOY_APP_NAME):$(tasks.app-version.results.output)
          value: image-registry.openshift-image-registry.svc:5000/pipelines-review/$(params.DEPLOY_APP_NAME):latest
        - name: DOCKERFILE
          value: Containerfile
        - name: CONTEXT
          value: $(params.APP_PATH)
        - name: TLSVERIFY
          value: "false"
        - name: SKIP_PUSH
          value: "true"
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared      

    - name: oc-deploy
      taskRef:
        name: maven-task
        kind: Task
      workspaces:
        - name: source
          workspace: shared
      params:
        - name: CONTEXT
          value: $(params.APP_PATH)
        # - name: ARGS
        #   value: install --no-package-lock
      runAfter:
        - build
    # - name: skopeo-copy
    #   taskRef:
    #     # TODO
    #   params:
    #     # TODO
