apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-java-pipeline
spec:
  workspaces:
    - name: shared
    # - name: maven_configs
  params:
    - name: GIT_REPO
      type: string
      default: "https://github.com/mikelo/DO288-apps"
    - name: GIT_REVISION
      type: string
      default: "pipeline"
    - name: APP_PATH
      type: string
      default: "builds-applications/apps/vertx-site"
    - name: DEPLOY_ARTIFACT_NAME
      type: string
      default: "target/vertx-site-1.0.0-SNAPSHOT-fat.jar"
    - name: DEPLOY_APP_NAME
      type: string
      default: "vertx-site"

  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: sslVerify
          value: "false"
      workspaces:
        - name: output
          workspace: shared
    - name: oc-deploy
      taskRef:
        name: openshift-client
        kind: Task
      workspaces:
        - name: output
          workspace: shared
      params:
        - name: CONTEXT
          value: $(params.APP_PATH)
        - name: APP_PATH
          value: $(params.APP_PATH)
        - name: DEPLOY_APP_NAME
          value: $(params.DEPLOY_APP_NAME)
        - name: DEPLOY_ARTIFACT_NAME
          value: $(params.DEPLOY_ARTIFACT_NAME)
        # - name: ARGS
        #   value: install --no-package-lock
      steps:
        - name: deploy
          # image: $(params.NODE_IMAGE)
          script: |
            cd  "$(workspaces.output.path)/$(params.APP_PATH)" || exit 1
            oc new-build --name=$(params.DEPLOY_APP_NAME) \
              -l app=$(params.DEPLOY_APP_NAME) --binary=true \
              --image-stream=openshift/java:8 || echo "BC already exists"
            oc start-build $(params.DEPLOY_APP_NAME) --wait=true \
                --from-file=$(params.DEPLOY_ARTIFACT_NAME)
            oc new-app $(params.DEPLOY_APP_NAME):latest \
                --name $(params.DEPLOY_APP_NAME) || echo "application exists"
            oc expose svc $(params.DEPLOY_APP_NAME) || echo "route exists"              
      runAfter:
        - fetch-repository
    # - name: skopeo-copy
    #   taskRef:
    #     # TODO
    #   params:
    #     # TODO
