apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-client
spec:
  workspaces:
    - name: source
  results:
    - name: output
  params:
  - name: CONTEXT
    type: string
    default: "."
  # - name: ARGS
  #   type: string
  - name: NODE_IMAGE
    type: string
    default: "quay.io/openshift/origin-cli:latest"
  - name: APP_PATH
    type: string
  - name: DEPLOY_APP_NAME
    type: string
  - name: DEPLOY_ARTIFACT_NAME
    type: string
  - name: IMAGE
    type: string
  steps:
    - name: build
      image: $(params.NODE_IMAGE)
      script: |
        # cd  "$(workspaces.manifest-dir.path)/$(params.APP_PATH)" || exit 1
        oc new-build --name=$(params.DEPLOY_APP_NAME) \
          -l app=$(params.DEPLOY_APP_NAME) --binary=true \
          --image-stream=$(params.DEPLOY_APP_NAME) || echo "BC already exists"
        oc start-build $(params.DEPLOY_APP_NAME) --wait=true \
            --from-file=$(params.DEPLOY_ARTIFACT_NAME)
        oc new-app $(params.DEPLOY_APP_NAME):latest \
            --name $(params.DEPLOY_APP_NAME) || echo "application exists"
        oc expose svc $(params.DEPLOY_APP_NAME) || echo "route exists"
      workingDir: $(workspaces.source.path)/$(params.CONTEXT)
      env:
        - name: CI
          value: "true"
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
