apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-client
spec:
  workspaces:
    - name: source
  results:
    - name: output
  params:
  - name: CONTEXT
    type: string
    default: "."
  # - name: ARGS
  #   type: string
  - name: NODE_IMAGE
    type: string
    default: "registry.access.redhat.com/ubi8/openjdk-11:1.16-3"
  steps:
    - name: build
      image: $(params.NODE_IMAGE)
      script: |
        cd  "$(workspaces.manifest-dir.path)/$(params.MVN_APP_PATH)" || exit 1
        oc new-build --name=$(params.DEPLOY_APP_NAME) \
          -l app=$(params.DEPLOY_APP_NAME) --binary=true \
          --image-stream=openshift/java:8 || echo "BC already exists"
        oc start-build $(params.DEPLOY_APP_NAME) --wait=true \
            --from-file=$(params.DEPLOY_ARTIFACT_NAME)
        oc new-app $(params.DEPLOY_APP_NAME):latest \
            --name $(params.DEPLOY_APP_NAME) || echo "application exists"
        oc expose svc $(params.DEPLOY_APP_NAME) || echo "route exists"
      workingDir: $(workspaces.source.path)/$(params.CONTEXT)
      env:
        - name: CI
          value: "true"
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
