apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-task
spec:
- name: CONTEXT
  type: string
  default: "."
- name: ARGS
  type: string
- name: NODE_IMAGE
  type: string
  default: "registry.access.redhat.com/ubi8/openjdk-11:1.16-3"
  steps:
    - name: build
      image: $(params.NODE_IMAGE)
      script: |
        ./oc-new-app.sh
      workingDir: $(workspaces.source.path)/$(params.CONTEXT)
      env:
        - name: CI
          value: "true"
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
